# Generated by Django 4.2.5 on 2023-09-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_note_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="full_name",),
    ]
